/*
 * Alfredo Ghana Economic Data: the article index, written by .github/workflows/article.yml.
 * Do not edit by hand.
 */
window.GDC_ARTICLES = {
  "updated": "2026-09-14T15:42:14.551Z",
  "articles": [
    {
      "date": "2026-09-14",
      "title": "Ghana's economy, week to 14 September 2026",
      "standfirst": "Public debt is running at about GH¢752.3bn, inflation stands at 5.0% for Aug 2026, and the policy rate is 14.0%. This briefing is assembled from the published figures on the dashboard, each with the date it belongs to.",
      "body": "## The debt\n\nGhana's public debt is estimated at **GH¢752.3bn** this morning. That is not a measurement: the Bank of Ghana's most recent published total is **GH¢719.5bn** at 30 June 2026, and the counter carries it forward at the pace debt grew between 31 December 2025 and 30 June 2026 — **GH¢5,014 a second**, or about GH¢433.2 million a day.\n\nAt that level, each of Ghana's roughly 34.4 million people carries about **GH¢21,869** of public debt. Debt-to-GDP was reported at 45.0% at the latest reading, against a peak of 61.8% at end-2024.\n\n## Prices and interest rates\n\nInflation was **5.0%** in Aug 2026 — up from 4.6% in Jul 2026. The Bank of Ghana's policy rate is **14.0%** (Jul 2026), which leaves a real policy rate of about **9.0 percentage points** once inflation is taken out.\n\nThe 91-day Treasury bill last cleared at **4.80%** (7 Sep 2026) — down from 6.68% in 4 Sep 2026. Petrol is **GH¢16.39** a litre (1 Sep 2026).\n\n## The cedi, reserves and commodities\n\nThe cedi traded at **GH¢11.4391** to the dollar on 13 September 2026, weaker than the 10.4500 recorded at End-2025 — a move of 9.5%.\n\nGross reserves stood at **US$12.9bn** (Jun 2026). Gold is trading at **US$4,368** an ounce and cocoa at **US$5,619** a tonne, as at 14 September 2026.\n\n## Trade\n\nExports reached **US$18.2bn** in H1 2026, of which gold alone was **US$12.5bn** — 69% of everything the country sold abroad. Against imports of about **US$9.4bn**, that leaves a trade surplus of **US$8.8bn**.\n\nThat concentration cuts both ways: the same gold price that has carried the surplus and steadied the cedi is a single market Ghana does not control.\n\n## The budget, so far\n\nThe 2026 budget approved **GH¢268.1bn** of revenue and grants against **GH¢302.5bn** of spending. Spread evenly, 70% of the year has passed, which puts revenue at about **GH¢188.5bn** and spending at **GH¢212.7bn** — an even-pace estimate, not collection to date.\n\nInterest on debt is budgeted at **GH¢57.7bn** for the year, which is **24.7%** of tax revenue: roughly 22 pesewas of every cedi the state collects.\n\n## What to watch\n\n- **Founder's Day** — 21 September 2026 (public holiday)\n- **Bank of Ghana rate decision** — 24 September 2026\n- **Budget statement** — 13 November 2026\n\n---\n\n*Every figure above carries the date of the release it came from. The debt figure is an estimate between monthly publications, worked out from the two most recent Bank of Ghana readings. Sources: Bank of Ghana, Ministry of Finance, Ghana Statistical Service and the other releases listed on the dashboard.*\n",
      "slug": "2026-09-14-weekly-brief",
      "file": "articles/2026-09-14-weekly-brief.md"
    },
    {
      "date": "2026-09-13",
      "title": "Ghana's economy, week to 13 September 2026",
      "standfirst": "Public debt is running at about GH¢752.0bn, inflation stands at 5.0% for Aug 2026, and the policy rate is 14.0%. This briefing is assembled from the published figures on the dashboard, each with the date it belongs to.",
      "body": "## The debt\n\nGhana's public debt is estimated at **GH¢752.0bn** this morning. That is not a measurement: the Bank of Ghana's most recent published total is **GH¢719.5bn** at 30 June 2026, and the counter carries it forward at the pace debt grew between 31 December 2025 and 30 June 2026 — **GH¢5,014 a second**, or about GH¢433.2 million a day.\n\nAt that level, each of Ghana's roughly 34.4 million people carries about **GH¢21,860** of public debt. Debt-to-GDP was reported at 45.0% at the latest reading, against a peak of 61.8% at end-2024.\n\n## Prices and interest rates\n\nInflation was **5.0%** in Aug 2026 — up from 4.6% in Jul 2026. The Bank of Ghana's policy rate is **14.0%** (Jul 2026), which leaves a real policy rate of about **9.0 percentage points** once inflation is taken out.\n\nThe 91-day Treasury bill last cleared at **4.80%** (7 Sep 2026) — down from 6.68% in 4 Sep 2026. Petrol is **GH¢16.39** a litre (1 Sep 2026).\n\n## The cedi, reserves and commodities\n\nThe cedi traded at **GH¢11.4391** to the dollar on 13 September 2026, weaker than the 10.4500 recorded at End-2025 — a move of 9.5%.\n\nGross reserves stood at **US$12.9bn** (Jun 2026). Gold is trading at **US$4,368** an ounce and cocoa at **US$5,619** a tonne, as at 13 September 2026.\n\n## Trade\n\nExports reached **US$18.2bn** in H1 2026, of which gold alone was **US$12.5bn** — 69% of everything the country sold abroad. Against imports of about **US$9.4bn**, that leaves a trade surplus of **US$8.8bn**.\n\nThat concentration cuts both ways: the same gold price that has carried the surplus and steadied the cedi is a single market Ghana does not control.\n\n## The budget, so far\n\nThe 2026 budget approved **GH¢268.1bn** of revenue and grants against **GH¢302.5bn** of spending. Spread evenly, 70% of the year has passed, which puts revenue at about **GH¢188.0bn** and spending at **GH¢212.1bn** — an even-pace estimate, not collection to date.\n\nInterest on debt is budgeted at **GH¢57.7bn** for the year, which is **24.7%** of tax revenue: roughly 22 pesewas of every cedi the state collects.\n\n## What to watch\n\n- **Founder's Day** — 21 September 2026 (public holiday)\n- **Bank of Ghana rate decision** — 24 September 2026\n\n---\n\n*Every figure above carries the date of the release it came from. The debt figure is an estimate between monthly publications, worked out from the two most recent Bank of Ghana readings. Sources: Bank of Ghana, Ministry of Finance, Ghana Statistical Service and the other releases listed on the dashboard.*\n",
      "slug": "2026-09-13-weekly-brief",
      "file": "articles/2026-09-13-weekly-brief.md"
    }
  ]
};
