/*
 * Alfredo Ghana Economic Data: what Alfredo says, in each language.
 *
 * SAFE TO EDIT BY HAND. Nothing overwrites this file.
 *
 * Every answer is a template. Anything in {braces} is filled in with a live figure —
 * keep the braces and their spelling exactly as they are; move them around the sentence
 * as the language needs. Any line you delete falls back to English, so a half-finished
 * translation is fine and never breaks the page.
 *
 * "ask" lists words a person might type or say in that language. They are matched on top
 * of the English words, never instead of them, so both always work.
 *
 * The Twi, Ewe, Ga and Hausa wordings below are a first pass and would be better for a
 * native speaker's eye. Correcting one is just editing the line.
 */
window.GDC_LANG = {
  en: {
    name: "English",
    speech: "en-GH",
    strings: {
      "ui.placeholder": "Ask about the debt, inflation, the cedi…",
      "ui.send": "Ask",
      "ui.listening": "Listening…",
      "ui.noSpeech": "I didn't catch that. Try again, or type it.",
      "ui.micBlocked": "The microphone is blocked. Allow it in your browser, or type the question.",
      "ui.micNone": "This browser can't listen. Chrome on Android or a desktop works best.",
      "greeting": "Hello — I'm <b>Alfredo</b>. Ask me about Ghana's debt, inflation, the cedi, trade or the budget, and I'll answer from the figures on this page, with the date each one belongs to.",
      "iam": "Yes, I am here. How can I help you today?",
      "thanks": "You’re welcome. Is there anything else I can help you with?",
      "bye": "Goodbye. Come back any time — the figures keep updating through the day.",
      "howareyou": "I am well, thank you. Ready with the figures whenever you are.",
      "hello": "Hello. I answer from the figures on this dashboard — debt, prices, the cedi, trade, the budget. Try one of the questions below, or type your own.",
      "help": "I read this site's own data: {count} published indicators, the debt readings, the budget, the national calendar and the annual series back to 1993. I can give you a figure, its date, how it has moved, and how the live counters are worked out. I don't browse the internet.",
      "unknown": "I don't hold that one. I can answer anything on this dashboard — any of the {count} published figures, the debt counters, the budget, trade, the calendar, or how a number is worked out. Try naming the figure, for example \"inflation\" or \"gold price\".",
      "debt.total": "<b>{now}</b> right now — a live estimate. It counts forward from the Bank of Ghana's {latestLabel} figure of {latest} at {perSecond} a second, the pace measured between {prevLabel} and {latestLabel}.",
      "debt.percap": "<b>{value}</b> per person, right now. That is the live debt estimate divided by a population estimate of {pop}.",
      "debt.household": "For a household of {n}: <b>{share}</b> of the debt, and {ytd} borrowed in their name so far this year.",
      "debt.domestic": "<b>{value}</b> of domestic debt, {share}% of the total at {label}.",
      "debt.external": "<b>{value}</b> of external debt, {share}% of the total. Most of it is in foreign currency, so a weaker cedi raises it without new borrowing.",
      "debt.ratio": "<b>{live}%</b> of GDP on the live estimate; {reported}% was reported at {label}, against a peak of {peak}% at {peakLabel}.",
      "debt.today": "<b>{value}</b> borrowed since midnight, at the current pace.",
      "debt.ytd": "<b>{value}</b> added since the {label} reading.",
      "debt.rate": "Debt is growing about <b>{perSecond} a second</b> — {perDay} million a day, on the pace between {prevLabel} and {latestLabel}.",
      "population": "About <b>{pop}</b> people, carried forward from the {source}'s projection of {base} million at 1 July 2026, growing {growth}% a year.",
      "method": "The counters are estimates between official releases. Debt counts forward from the {label} reading at the pace measured over the previous {months} months. Budget lines spread the approved annual figures evenly across the year. Every published reading on the page carries its own date, and anything past its usual release interval is marked <b>Update due</b>.",
      "budget": "<b>{label}: {value}</b> approved for {year}, or about {toDate} spread to today.",
      "trade": "Exports <b>US${exports}bn</b> in {period}, of which gold was US${gold}bn. Imports about <b>US${imports}bn</b>, leaving a surplus of US${surplus}bn.",
      "calendar": "Next up: {list}.",
      "calendar.item": "<b>{name}</b> on {date}",
      "news": "Latest business headlines:",
      "africa.country": "<b>{country}: {value}%</b> ({period}) against Ghana's {ghana}% ({ghanaPeriod}) — Ghana is {gap} points {direction}. Latest published month for each, year on year.",
      "africa.rank": "Ghana's inflation of <b>{ghana}%</b> ({period}) is {rank} highest of {count} African countries. Highest: {highest} at {highestValue}%. Lowest: {lowest} at {lowestValue}%.",
      "reading": "<b>{label}: {value}</b> <span class=\"alf-date\">{date}</span>",
      "reading.live": "Market right now: {value}, quoted {time}.",
      "reading.up": "Up from {from} in {fromDate}.",
      "reading.down": "Down from {from} in {fromDate}.",
      "reading.flat": "Unchanged from {fromDate}.",
      "reading.range": "Since {since}: highest {high}, lowest {low}.",
      "higher": "higher",
      "lower": "lower",
      "reading.from": "Source: {source} · {date}.",
      "reading.open": "See the full figure",
      "reading.fromShort": "{source}",
      "unknown.near": "I'm not certain I hold that one. Did you mean:",
      "follow.why": "On <b>{label}</b>:",
      "follow.source": "<b>{label}</b> comes from:",
      "change": "<b>{label}</b> {direction} from {from} in {fromDate} to {to} in {toDate} — a move of {gap}.",
      "change.pct": "A change of {pct}%.",
      "rose": "rose",
      "fell": "fell",
      "held": "held steady",
      "extreme.high": "<b>{label}</b> was at its highest, {value}, in {date} — of everything held since {since}. It stands at {now} now ({nowDate}).",
      "extreme.low": "<b>{label}</b> was at its lowest, {value}, in {date} — of everything held since {since}. It stands at {now} now ({nowDate}).",
      "compare": "<b>{a}: {av}</b> <span class=\"alf-date\">{ad}</span> against <b>{b}: {bv}</b> <span class=\"alf-date\">{bd}</span>",
      "compare.gap": "{higher} is the higher of the two, by {gap}.",
      "real.rate": "The policy rate is <b>{policy}%</b> ({policyDate}) and inflation <b>{inflation}%</b> ({inflationDate}), so the real rate is about <b>{real}%</b> {direction} inflation.",
      "above": "above",
      "below": "below",
      "africa.gdp": "{country}'s economy is about US${gdp}bn ({year}).",
      "africa.open": "Open the Africa portal",
      "voice.none": "This device has no {language} voice installed, so I am reading in English. The words on screen are still {language}.",
      "note.figures": ""
    },
    voiceHints: [],
    labels: {},
    suggestions: [
      "What is the debt right now?", "How much does each person owe?", "What is inflation?",
      "Cedi to the dollar", "Compare exports and imports", "When is the next holiday?",
      "How is the debt worked out?",
      "Is the policy rate above inflation?", "When was inflation highest?"
    ],
    ask: {}
  },

  tw: {
    name: "Twi",
    speech: "ak-GH",
    strings: {
      "ui.placeholder": "Bisa ka, ɛboɔ anaa dɔla ho asɛm…",
      "ui.send": "Bisa",
      "ui.listening": "Meretie…",
      "ui.noSpeech": "Mante. Ka bio, anaa twerɛ.",
      "ui.micBlocked": "Wɔasi mikrofon no kwan. Ma ho kwan wɔ wo browser mu, anaa twerɛ asɛmmisa no.",
      "ui.micNone": "Browser yi ntumi ntie. Chrome a ɛwɔ Android anaa computer so yɛ pa.",
      "greeting": "Akwaaba — me din de <b>Alfredo</b>. Bisa me Ghana ka, ɛboɔ a ɛreforo, dɔla, adetɔn anaa sikasɛm ho, na mede akontaa a ɛwɔ krataa yi so bɛbua wo, ne da a wɔtoo biara.",
      "iam": "Aane, mewɔ ha. Ɛdeɛn na metumi ayɛ ama wo ɛnnɛ?",
      "thanks": "Yɛda wo ase. Biribi foforɔ wɔ hɔ a metumi aboa wo?",
      "bye": "Nante yie. Bra bio berɛ biara — akontaa no sesa da biara.",
      "howareyou": "Me ho yɛ, medaase. Mesiesie akontaa no ama wo berɛ biara.",
      "hello": "Akwaaba. Mede akontaa a ɛwɔ krataa yi so na ɛbua — ka, ɛboɔ, dɔla, adetɔn ne sikasɛm. Sɔ nsɛmmisa a ɛwɔ ase hɔ bi hwɛ, anaa twerɛ wo deɛ.",
      "help": "Mekenkan krataa yi ankasa akontaa: nneɛma {count} a wɔatintim, ka no nsusuiɛ, sikasɛm, ɔman no da ahodoɔ ne mfeɛ nyinaa firi 1993. Metumi ka akontaa bi, ne da, sɛdeɛ ɛkɔ soro anaa fam, ne sɛdeɛ wɔbu akontaa no. Menkɔ intanɛt so.",
      "unknown": "Menni saa biribi no. Metumi abua biribiara a ɛwɔ krataa yi so — akontaa {count} no mu biara, ka no, sikasɛm, adetɔn, da ahodoɔ, anaa sɛdeɛ wɔbu akontaa bi. Bɔ akontaa no din, sɛ nhwɛsoɔ \"ɛboɔ a ɛreforo\" anaa \"sika kɔkɔɔ boɔ\".",
      "debt.total": "<b>{now}</b> seesei ara — nsusuiɛ a ɛrekɔ so. Ɛfiri Ghana Sikakorabea {latestLabel} akontaa {latest} so kɔ, {perSecond} sekan biara, sɛdeɛ ɛkɔɔ so wɔ {prevLabel} ne {latestLabel} ntam.",
      "debt.percap": "<b>{value}</b> ma onipa biara, seesei ara. Ɛyɛ ka no nsusuiɛ a wɔakyekyɛ mu ama nnipa dodoɔ {pop}.",
      "debt.household": "Efie a nnipa {n} wɔ mu: <b>{share}</b> wɔ ka no mu, na wɔabɔ {ytd} bosome yi mu wɔ wɔn din mu.",
      "debt.domestic": "<b>{value}</b> yɛ ka a ɛwɔ ɔman mu, {share}% wɔ ne nyinaa mu wɔ {label}.",
      "debt.external": "<b>{value}</b> yɛ ka a ɛwɔ aman foforɔ so, {share}% wɔ ne nyinaa mu. Dodoɔ no ara wɔ amannɔne sika mu, enti sɛ sidi no tew a, ɛma ka no kɔ soro a wɔammɔ bosea foforɔ.",
      "debt.ratio": "<b>{live}%</b> wɔ GDP so wɔ nsusuiɛ yi so; wɔkaa {reported}% wɔ {label}, na ne soro koraa yɛ {peak}% wɔ {peakLabel}.",
      "debt.today": "<b>{value}</b> na wɔabɔ firi anadwo dasuom, sɛdeɛ ɛrekɔ so seesei.",
      "debt.ytd": "<b>{value}</b> na aka ho firi {label} akontaa no so.",
      "debt.rate": "Ka no rekɔ soro bɛyɛ <b>{perSecond} sekan biara</b> — ɔpepem {perDay} da biara, wɔ {prevLabel} ne {latestLabel} ntam nkɔso so.",
      "population": "Bɛyɛ nnipa <b>{pop}</b>, a ɛfiri {source} nsusuiɛ a ɛyɛ ɔpepem {base} wɔ 1 July 2026, na ɛkɔ soro {growth}% afe biara.",
      "method": "Akontaa yi yɛ nsusuiɛ wɔ amanneɛbɔ ahodoɔ ntam. Ka no firi {label} akontaa no so kɔ, sɛdeɛ ɛkɔɔ so wɔ abosome {months} a atwam no mu. Sikasɛm no, wɔkyekyɛ afe no akontaa mu pɛpɛɛpɛ ma afe no nyinaa. Akontaa biara wɔ ne da, na deɛ ne berɛ atwam no, wɔatwerɛ <b>Update due</b> wɔ so.",
      "budget": "<b>{label}: {value}</b> na wɔapene so ama {year}, na ɛbɛyɛ {toDate} deduru ɛnnɛ.",
      "trade": "Adetɔn a wɔtɔn kɔɔ abɔnten <b>US${exports}bn</b> wɔ {period} mu, na sika kɔkɔɔ yɛ US${gold}bn wɔ mu. Nneɛma a wɔtɔeɛ bɛyɛ <b>US${imports}bn</b>, enti mfasoɔ yɛ US${surplus}bn.",
      "calendar": "Deɛ ɛdi hɔ: {list}.",
      "calendar.item": "<b>{name}</b> wɔ {date}",
      "news": "Adwuma ne sikasɛm nsɛm foforɔ:",
      "africa.country": "<b>{country}: {value}%</b> ({period}) na Ghana deɛ yɛ {ghana}% ({ghanaPeriod}) — Ghana deɛ no {direction} {gap} points.",
      "africa.rank": "Ghana ɛboɔ a ɛreforo <b>{ghana}%</b> ({period}) yɛ {rank} a ɛkorɔn wɔ Afrika aman {count} mu. Ɛsoro koraa: {highest}, {highestValue}%. Ɛfam koraa: {lowest}, {lowestValue}%.",
      "reading": "<b>{label}: {value}</b> <span class=\"alf-date\">{date}</span>",
      "reading.live": "Seesei dwadi mu: {value}, {time}.",
      "reading.up": "Ɛkɔɔ soro firi {from} wɔ {fromDate}.",
      "reading.down": "Ɛtee firi {from} wɔ {fromDate}.",
      "reading.flat": "Ɛnsesaa firi {fromDate}.",
      "reading.range": "Firi {since}: ne soro {high}, ne fam {low}.",
      "higher": "korɔn",
      "lower": "ba fam",
      "reading.from": "Ɛfiri: {source} · {date}.",
      "reading.open": "Hwɛ akontaa no nyinaa",
      "reading.fromShort": "{source}",
      "unknown.near": "Mennim saa no yie. Ebia wopɛ sɛ wobisa:",
      "follow.why": "<b>{label}</b> ho asɛm:",
      "follow.source": "<b>{label}</b> firi:",
      "change": "<b>{label}</b> {direction} firi {from} ({fromDate}) kɔ {to} ({toDate}) — nsakraeɛ yɛ {gap}.",
      "change.pct": "Ɛyɛ {pct}%.",
      "rose": "kɔɔ soro",
      "fell": "tee",
      "held": "ansesa",
      "extreme.high": "<b>{label}</b> kɔɔ soro koraa, {value}, wɔ {date} — firi {since}. Seesei ɛyɛ {now} ({nowDate}).",
      "extreme.low": "<b>{label}</b> baa fam koraa, {value}, wɔ {date} — firi {since}. Seesei ɛyɛ {now} ({nowDate}).",
      "compare": "<b>{a}: {av}</b> <span class=\"alf-date\">{ad}</span> ne <b>{b}: {bv}</b> <span class=\"alf-date\">{bd}</span>",
      "compare.gap": "{higher} na ɛkorɔn, ɛboro so {gap}.",
      "real.rate": "Sikakorabea ɛboɔ yɛ <b>{policy}%</b> ({policyDate}), na ɛboɔ a ɛreforo yɛ <b>{inflation}%</b> ({inflationDate}), enti mfasoɔ ankasa yɛ bɛyɛ <b>{real}%</b> {direction}.",
      "above": "wɔ soro",
      "below": "wɔ fam",
      "africa.gdp": "{country} sikasɛm yɛ bɛyɛ US${gdp}bn ({year}).",
      "africa.open": "Bue Afrika krataa no",
      "voice.none": "Afidie yi nni {language} nne, enti mekenkan wɔ Borɔfo mu. Nsɛm a ɛwɔ krataa no so deɛ, ɛda so yɛ {language}.",
      "note.figures": "Akontaa din bi da so wɔ Borɔfo kasa mu."
    },
    voiceHints: ["ak", "tw", "en-GH", "en-NG"],
    labels: {
      "Inflation": "Ɛboɔ a ɛreforo",
      "Food inflation": "Aduane boɔ foro",
      "BoG policy rate": "Sikakorabea mfɛntom",
      "91-day T-bill": "Nna 91 T-bill",
      "364-day T-bill": "Nna 364 T-bill",
      "US dollar": "Amerika dɔla",
      "British pound": "Britani pɔn",
      "Euro": "Euro",
      "Gold price": "Sika kɔkɔɔ boɔ",
      "Cocoa world price": "Kookoo boɔ wɔ wiase",
      "Petrol": "Petrol",
      "Diesel": "Diesel",
      "Cooking gas (LPG)": "Gyaa (LPG)",
      "Daily minimum wage": "Da biara akatua ketewa",
      "Gross reserves": "Sika a wɔakora",
      "Trade surplus": "Adetɔn mfasoɔ",
      "Real GDP growth": "Sikasɛm nkɔso",
      "Unemployment rate": "Adwuma a ɛnni hɔ"
    },
    suggestions: [
      "Ka no dodoɔ seesei?", "Onipa biara ka ne sɛn?", "Ɛboɔ a ɛreforo yɛ sɛn?",
      "Dɔla ne sidi", "Adetɔn ne adetɔ", "Da kɛseɛ a ɛdi hɔ?",
      "Sikakorabea ɛboɔ korɔn sen ɛboɔ a ɛreforo?", "Ɛboɔ a ɛreforo kɔɔ soro koraa berɛ bɛn?"
    ],
    ask: {
      debt: ["ka", "ɛka", "bosea", "ka a yɛde"],
      percap: ["onipa biara", "obiara ka"],
      inflation: ["ɛboɔ", "eboɔ", "ɛboɔ foro", "bo foro"],
      dollar: ["dɔla", "dola", "sidi"],
      population: ["nnipa dodoɔ", "dodoɔ"],
      holiday: ["da kɛseɛ", "afahyɛ", "ahomegye da"],
      trade: ["adetɔn", "adetɔ", "ɛdwa"],
      budget: ["sikasɛm", "sika nhyehyɛeɛ", "tow"],
      hello: ["akwaaba", "ete sen", "ɛte sɛn", "maakye", "maaha", "maadwo"],
      help: ["boa me", "wo yɛ hwan", "dɛn na wotumi yɛ"],
      thanks: ["medaase", "meda wo ase", "yɛda wo ase", "daase"],
      bye: ["nante yie", "yɛbɛhyia", "da yie", "mekɔ"],
      howareyou: ["wo ho te sɛn", "wo ho ye"]
    }
  },

  ee: {
    name: "Ewe",
    speech: "ee-GH",
    strings: {
      "ui.placeholder": "Bia fe, asixɔxɔ alo dollar ŋu nya…",
      "ui.send": "Bia",
      "ui.listening": "Mele ese…",
      "ui.noSpeech": "Nyemese o. Gblɔe ake, alo ŋlɔe.",
      "ui.micBlocked": "Wotu mikrofon la ƒe mɔ. Ɖe mɔ nɛ le wò browser me, alo ŋlɔ nyabiabia la.",
      "ui.micNone": "Browser sia mate ŋu ase nu o. Chrome le Android alo kɔmpiuta dzi nyo wu.",
      "greeting": "Woezɔ — <b>Alfredo</b> ye menye. Bia Ghana ƒe fe, asixɔxɔ, dollar, asitsatsa alo gadidi ŋu nya, eye maɖo eŋu kple xexlẽdzesi siwo le axa sia dzi, kple ŋkeke si wotso.",
      "iam": "Ɛ̃, mele afi sia. Nu ka mate ŋu awɔ na wò egbea?",
      "thanks": "Akpe na wò. Nane bubu li si mate ŋu akpe ɖe ŋuwòa?",
      "bye": "Hede nyuie. Trɔ va ɣe sia ɣi — xexlẽdzesiwo trɔna gbe sia gbe.",
      "howareyou": "Mele nyuie, akpe. Mele klalo kple xexlẽdzesiwo ɣe sia ɣi.",
      "hello": "Woezɔ. Metsɔa xexlẽdzesi siwo le axa sia dzi ɖo nya ŋu — fe, asixɔxɔ, dollar, asitsatsa kple gadidi. Te nyabiase siwo le ete kpɔ, alo ŋlɔ tɔwò.",
      "help": "Mexlẽa axa sia ŋutɔ ƒe nyatakakawo: nusi wota {count}, fe ƒe xexlẽdzesiwo, gadidi, dukɔa ƒe ŋkekewo kple ƒe sia ƒe tso 1993. Mate ŋu agblɔ xexlẽdzesi aɖe, eƒe ŋkeke, alesi wòtrɔ, kple alesi wobua nuawoe. Nyemeyia internet dzi o.",
      "unknown": "Nyemelé ema o. Mate ŋu aɖo nya sia nya si le axa sia dzi ŋu — xexlẽdzesi {count} la dometɔ ɖe sia ɖe, fe, gadidi, asitsatsa, ŋkekewo, alo alesi wobua xexlẽdzesi aɖe. Yɔ xexlẽdzesi la ŋkɔ, le kpɔɖeŋu me \"asixɔxɔ\" alo \"sika ƒe asi\".",
      "debt.total": "<b>{now}</b> fifi laa — akɔnta si le yiyim. Etso Ghana Gadzraɖoƒe ƒe {latestLabel} xexlẽdzesi {latest} dzi, {perSecond} le sekend ɖe sia ɖe me, abe alesi wòyi le {prevLabel} kple {latestLabel} dome ene.",
      "debt.percap": "<b>{value}</b> na ame ɖe sia ɖe, fifi laa. Enye fe la ƒe akɔnta si wòma ɖe amewo {pop} dzi.",
      "debt.household": "Aƒe si me ame {n} le: <b>{share}</b> le fe la me, eye wodo {ytd} le woƒe ŋkɔ me le ƒe sia me.",
      "debt.domestic": "<b>{value}</b> nye fe si le dukɔa me, {share}% le esiawo katã me le {label}.",
      "debt.external": "<b>{value}</b> nye fe si le duta, {share}% le esiawo katã me. Wo akpa gãtɔ le dutaga me, eya ta ne cedi ƒe asi ɖiɖi la, fe la dzina evɔ womedo ga yeye o.",
      "debt.ratio": "<b>{live}%</b> le GDP dzi le akɔnta sia nu; {reported}% wogblɔ le {label}, evɔ eƒe kɔkɔƒe kekeake nye {peak}% le {peakLabel}.",
      "debt.today": "<b>{value}</b> wodo tso zãtitina ke, abe alesi wòle yiyim fifia ene.",
      "debt.ytd": "<b>{value}</b> wotsɔ kpee tso {label} ƒe xexlẽdzesi la dzi.",
      "debt.rate": "Fe la le dzidzim abe <b>{perSecond} le sekend ɖe sia ɖe me</b> ene — miliɔn {perDay} le ŋkeke ɖeka me, le {prevLabel} kple {latestLabel} dome.",
      "population": "Ame <b>{pop}</b> lɔƒo, tso {source} ƒe akɔnta si nye miliɔn {base} le July 1, 2026, si le dzidzim {growth}% le ƒe sia ƒe me.",
      "method": "Xexlẽdzesi siawo nye akɔnta siwo le dukɔa ƒe nyatakakawo dome. Fe la tso {label} ƒe xexlẽdzesi dzi, abe alesi wòyi le ɣleti {months} siwo va yi me ene. Gadidi ƒe akpawo, woma ƒea ƒe akɔnta ɖe ƒea katã dzi sɔsɔe. Xexlẽdzesi ɖe sia ɖe kple eƒe ŋkeke, eye ne eƒe ɣeyiɣi va yi la, woŋlɔ <b>Update due</b> ɖe edzi.",
      "budget": "<b>{label}: {value}</b> woda ɖi na {year}, si anye {toDate} va se ɖe egbe.",
      "trade": "Nu siwo wodzra ɖe duta <b>US${exports}bn</b> le {period} me, sika nye US${gold}bn le eme. Nu siwo woƒle tso duta anye <b>US${imports}bn</b>, eya ta viɖe la nye US${surplus}bn.",
      "calendar": "Esi gbɔna: {list}.",
      "calendar.item": "<b>{name}</b> le {date}",
      "news": "Asitsatsa ŋuti nyadzɔdzɔ yeyeawo:",
      "africa.country": "<b>{country}: {value}%</b> ({period}) le Ghana tɔ {ghana}% ({ghanaPeriod}) ŋu — Ghana tɔ {direction} kple point {gap}.",
      "africa.rank": "Ghana ƒe asixɔxɔ dzidzi <b>{ghana}%</b> ({period}) nye {rank} kɔkɔtɔ le Afrika dukɔ {count} dome. Kɔkɔtɔ kekeake: {highest}, {highestValue}%. Ɖetɔ kekeake: {lowest}, {lowestValue}%.",
      "reading": "<b>{label}: {value}</b> <span class=\"alf-date\">{date}</span>",
      "reading.live": "Asi si le fifia: {value}, {time}.",
      "reading.up": "Edzi tso {from} le {fromDate}.",
      "reading.down": "Eɖiɖi tso {from} le {fromDate}.",
      "reading.flat": "Metrɔ tso {fromDate} o.",
      "reading.range": "Tso {since}: kɔkɔtɔ {high}, ɖetɔ {low}.",
      "higher": "kɔkɔ wu",
      "lower": "ɖe anyi wu",
      "reading.from": "Tso: {source} · {date}.",
      "reading.open": "Kpɔ xexlẽdzesi bliboa",
      "reading.fromShort": "{source}",
      "unknown.near": "Nyemeka ɖe edzi be mele asinye o. Ɖe nèdi be nàbia:",
      "follow.why": "Le <b>{label}</b> ŋu:",
      "follow.source": "<b>{label}</b> tso:",
      "change": "<b>{label}</b> {direction} tso {from} ({fromDate}) va ɖo {to} ({toDate}) — tɔtrɔ la nye {gap}.",
      "change.pct": "Esia nye {pct}%.",
      "rose": "dzi",
      "fell": "ɖiɖi",
      "held": "meɖi tso o",
      "extreme.high": "<b>{label}</b> kɔ wu le {value} me le {date} — tso {since}. Fifia enye {now} ({nowDate}).",
      "extreme.low": "<b>{label}</b> ɖe anyi wu le {value} me le {date} — tso {since}. Fifia enye {now} ({nowDate}).",
      "compare": "<b>{a}: {av}</b> <span class=\"alf-date\">{ad}</span> kple <b>{b}: {bv}</b> <span class=\"alf-date\">{bd}</span>",
      "compare.gap": "{higher} kɔ wu, kple {gap}.",
      "real.rate": "Gadzraɖoƒe ƒe asixɔxɔ nye <b>{policy}%</b> ({policyDate}), eye asixɔxɔdzidzi nye <b>{inflation}%</b> ({inflationDate}), eya ta asixɔxɔ vavãtɔ nye <b>{real}%</b> {direction}.",
      "above": "kɔ wu",
      "below": "ɖe anyi wu",
      "africa.gdp": "{country} ƒe ganyawo le US${gdp}bn lɔƒo ({year}).",
      "africa.open": "Ʋu Afrika ƒe axa",
      "voice.none": "Mɔ̃ sia me {language} gbe aɖeke mele o, eya ta mexlẽ le Eŋlisigbe me. Nya siwo le axa dzi la gakpɔtɔ le {language} me.",
      "note.figures": "Xexlẽdzesiwo ƒe ŋkɔ aɖewo gale Eŋlisigbe me."
    },
    voiceHints: ["ee", "en-GH", "en-NG"],
    labels: {
      "Inflation": "Asixɔxɔ dzidzi",
      "Food inflation": "Nuɖuɖu ƒe asixɔxɔ dzidzi",
      "BoG policy rate": "Gadzraɖoƒe ƒe deme",
      "US dollar": "Amerika dollar",
      "British pound": "Britania pound",
      "Euro": "Euro",
      "Gold price": "Sika ƒe asi",
      "Cocoa world price": "Kuku ƒe asi le xexeame",
      "Petrol": "Petrol",
      "Diesel": "Diesel",
      "Cooking gas (LPG)": "Nuɖaƒe gas (LPG)",
      "Daily minimum wage": "Gbe sia gbe fetu suetɔ",
      "Gross reserves": "Dutaga si wodzra ɖo",
      "Trade surplus": "Asitsatsa ƒe viɖe",
      "Real GDP growth": "Ganyawo ƒe dzidzi (GDP)",
      "Unemployment rate": "Dɔwɔwɔ manɔamesi"
    },
    suggestions: [
      "Fe la nye nukae fifia?", "Ame ɖe sia ɖe nyi fe nenie?", "Asixɔxɔ dzidzi nye nenie?",
      "Dollar kple cedi", "Nudzradzra kple nuƒoƒle", "Ŋkeke gã si gbɔna?",
      "Ɖe gadzraɖoƒe ƒe asixɔxɔ kɔ wu asixɔxɔdzidzia?", "Ɣekaɣi asixɔxɔdzidzi kɔ wu?"
    ],
    ask: {
      debt: ["fe", "fenyinyi", "ga si wonyi"],
      inflation: ["asixɔxɔ", "asi dzi dzi", "nuxɔxɔ"],
      dollar: ["dollar", "cedi"],
      population: ["amewo ƒe xexlẽme", "ame nenie"],
      holiday: ["ŋkeke gã", "mɔkeke"],
      trade: ["asitsatsa", "nudzradzra", "nuƒoƒle"],
      budget: ["gadidi", "adzɔ"],
      hello: ["woezɔ", "ŋdi", "ŋdɔ", "fiẽ"],
      help: ["kpe ɖe ŋunye", "ame kae nènye"],
      thanks: ["akpe", "akpe na wò", "akpe kaka"],
      bye: ["hede nyuie", "miado go", "medzo"],
      howareyou: ["èfɔa", "aleke nèle"]
    }
  },

  gaa: {
    name: "Ga",
    speech: "gaa-GH",
    strings: {
      "ui.placeholder": "Bi nyɔmɔ, jara loo dollar he sane…",
      "ui.send": "Bi",
      "ui.listening": "Miinu…",
      "ui.noSpeech": "Minuuu. Wiemɔ ekoŋŋ, loo ŋmala.",
      "ui.micBlocked": "Atsĩ mikrofon lɛ naa. Ha gbɛ yɛ o browser lɛ mli, loo ŋmaa sanebimɔ lɛ.",
      "ui.micNone": "Browser nɛɛ nyɛŋ ebo toi. Chrome yɛ Android loo kɔmputa nɔ hi fe.",
      "greeting": "Ojekoo — miji <b>Alfredo</b>. Bi mi Ghana nyɔmɔ, jara ni miiwo nɔ, dollar, nitsumɔ loo shika gbɛjianɔtoo he sane, ni makɛ akɔntabuu ni yɔɔ baafo nɛɛ nɔ aha bo, kɛ gbi ni akɛto lɛ.",
      "iam": "Hɛɛ, miyɛ biɛ. Mɛni manyɛ maha bo ŋmɛnɛ?",
      "thanks": "Oyiwaladɔŋŋ. Nɔ ko yɛ ni manyɛ maha bo?",
      "bye": "Yaa oyaawɔ. Ba ekoŋ be mli fɛɛ — akɔntabuu lɛ tsakeɔ daa gbi.",
      "howareyou": "Miyɛ ojogbaŋŋ, oyiwaladɔŋŋ. Misaa akɔntabuu lɛ maha bo be fɛɛ be.",
      "hello": "Ojekoo. Mikɛ akɔntabuu ni yɔɔ baafo nɛɛ nɔ haa hetoo — nyɔmɔ, jara, dollar, nitsumɔ kɛ shika gbɛjianɔtoo. Kaa sanebimɔi ni yɔɔ shishi lɛ ekome, loo ŋmala bo nɔ̃.",
      "help": "Mikaneɔ baafo nɛɛ diɛŋtsɛ akɔntabuu: nibii {count} ni akɛto, nyɔmɔ akɔntabuu, shika gbɛjianɔtoo, maŋ gbii lɛ kɛ afii fɛɛ kɛjɛ 1993. Manyɛ makɛ akɔntabuu ko, egbi, bɔ ni etsɔɔ, kɛ bɔ ni abuɔ lɛ. Miyaaa intanɛt nɔ.",
      "unknown": "Miyɛɛɛ nɔ nɛɛ. Manyɛ mahã nɔ fɛɛ nɔ ni yɔɔ baafo nɛɛ nɔ hetoo — akɔntabuu {count} lɛ ateŋ ekome fɛɛ ekome, nyɔmɔ, shika gbɛjianɔtoo, nitsumɔ, gbii lɛ, loo bɔ ni abuɔ akɔntabuu ko. Tsɛ akɔntabuu lɛ gbɛi, akɛ nɔkwɛmɔnɔ \"jara ni miiwo nɔ\" loo \"shika tsuru jara\".",
      "debt.total": "<b>{now}</b> amrɔ nɛɛ — akɔntabuu ni miiya nɔ. Ejɛ Ghana Shikatoohe lɛ {latestLabel} akɔntabuu {latest} nɔ, {perSecond} yɛ sɛkɛnd fɛɛ sɛkɛnd mli, taakɛ eya nɔ yɛ {prevLabel} kɛ {latestLabel} teŋ lɛ.",
      "debt.percap": "<b>{value}</b> kɛha mɔ fɛɛ mɔ, amrɔ nɛɛ. Eji nyɔmɔ lɛ ni aja mli aha gbɔmɛi {pop}.",
      "debt.household": "Shia ni mɛi {n} yɔɔ mli: <b>{share}</b> yɛ nyɔmɔ lɛ mli, ni akɛ {ytd} efata he yɛ amɛgbɛi anɔ yɛ afi nɛɛ mli.",
      "debt.domestic": "<b>{value}</b> ji nyɔmɔ ni yɔɔ maŋ lɛ mli, {share}% yɛ fɛɛ lɛ mli yɛ {label}.",
      "debt.external": "<b>{value}</b> ji nyɔmɔ ni yɔɔ maji krokomɛi anɔ, {share}% yɛ fɛɛ lɛ mli. Babaoo yɛ maŋsɛɛ shika mli, no hewɔ kɛ cedi jara ba shi lɛ, nyɔmɔ lɛ teɔ shi ni akɛ shika hee efataaa he.",
      "debt.ratio": "<b>{live}%</b> yɛ GDP nɔ yɛ akɔntabuu nɛɛ naa; {reported}% ni awie yɛ {label}, shi enɔkwale kwɔkwɔɔ ji {peak}% yɛ {peakLabel}.",
      "debt.today": "<b>{value}</b> ni akɛ efata he kɛjɛ nyɔɔŋteŋ, taakɛ eyaa nɔ amrɔ nɛɛ.",
      "debt.ytd": "<b>{value}</b> ni efata he kɛjɛ {label} akɔntabuu lɛ nɔ.",
      "debt.rate": "Nyɔmɔ lɛ miiya nɔ aaafee <b>{perSecond} yɛ sɛkɛnd fɛɛ mli</b> — akpekpei {perDay} yɛ gbi fɛɛ gbi, yɛ {prevLabel} kɛ {latestLabel} teŋ.",
      "population": "Aaafee gbɔmɛi <b>{pop}</b>, ni ejɛ {source} akɔntabuu ni ji akpekpei {base} yɛ July 1, 2026, ni miiya nɔ {growth}% yɛ afi fɛɛ afi mli.",
      "method": "Akɔntabuu nɛɛ ji susumɔ yɛ maŋ amaniɛbɔi ateŋ. Nyɔmɔ lɛ jɛɔ {label} akɔntabuu lɛ nɔ, taakɛ eya nɔ yɛ nyɔji {months} ni eho lɛ amli. Shika gbɛjianɔtoo lɛ, aja afi lɛ akɔntabuu mli pɛpɛɛpɛ kɛha afi lɛ fɛɛ. Akɔntabuu fɛɛ kɛ egbi yɔɔ, ni kɛ ebe lɛ eho lɛ, aŋmala <b>Update due</b> yɛ nɔ.",
      "budget": "<b>{label}: {value}</b> ni akpɛlɛ nɔ kɛha {year}, ni eeefee {toDate} kɛbashi ŋmɛnɛ.",
      "trade": "Nibii ni ahɔɔ kɛtee maji krokomɛi anɔ ji <b>US${exports}bn</b> yɛ {period} mli, ni shika tsuru ji US${gold}bn yɛ mli. Nibii ni aje maji krokomɛi anɔ aaafee <b>US${imports}bn</b>, no hewɔ sɛɛnamɔ ji US${surplus}bn.",
      "calendar": "Nɔ ni nyiɛ sɛɛ: {list}.",
      "calendar.item": "<b>{name}</b> yɛ {date}",
      "news": "Nitsumɔ he saji heei:",
      "africa.country": "<b>{country}: {value}%</b> ({period}) shi Ghana nɔ̃ ji {ghana}% ({ghanaPeriod}) — Ghana nɔ̃ lɛ {direction} kɛ point {gap}.",
      "africa.rank": "Ghana jara ni miiwo nɔ <b>{ghana}%</b> ({period}) ji {rank} ni kwɔ yɛ Afrika maji {count} ateŋ. Nɔ ni kwɔ fe fɛɛ: {highest}, {highestValue}%. Nɔ ni ba shi fe fɛɛ: {lowest}, {lowestValue}%.",
      "reading": "<b>{label}: {value}</b> <span class=\"alf-date\">{date}</span>",
      "reading.live": "Amrɔ nɛɛ jara: {value}, {time}.",
      "reading.up": "Ete shi kɛjɛ {from} yɛ {fromDate}.",
      "reading.down": "Eba shi kɛjɛ {from} yɛ {fromDate}.",
      "reading.flat": "Etsakeee kɛjɛ {fromDate}.",
      "reading.range": "Kɛjɛ {since}: nɔ ni kwɔ fe fɛɛ {high}, nɔ ni ba shi fe fɛɛ {low}.",
      "higher": "kwɔ",
      "lower": "ba shi",
      "reading.from": "Ejɛ: {source} · {date}.",
      "reading.open": "Kwɛ akɔntabuu lɛ fɛɛ",
      "reading.fromShort": "{source}",
      "unknown.near": "Minyɛɛɛ jogbaŋŋ. Ekolɛ oosumɔ obi:",
      "follow.why": "<b>{label}</b> he sane:",
      "follow.source": "<b>{label}</b> jɛ:",
      "change": "<b>{label}</b> {direction} kɛjɛ {from} ({fromDate}) kɛyaa {to} ({toDate}) — tsakemɔ lɛ ji {gap}.",
      "change.pct": "Enɛ ji {pct}%.",
      "rose": "wo nɔ",
      "fell": "ba shi",
      "held": "etsakeee",
      "extreme.high": "<b>{label}</b> kwɔ fe fɛɛ, {value}, yɛ {date} — kɛjɛ {since}. Amrɔ nɛɛ eji {now} ({nowDate}).",
      "extreme.low": "<b>{label}</b> ba shi fe fɛɛ, {value}, yɛ {date} — kɛjɛ {since}. Amrɔ nɛɛ eji {now} ({nowDate}).",
      "compare": "<b>{a}: {av}</b> <span class=\"alf-date\">{ad}</span> kɛ <b>{b}: {bv}</b> <span class=\"alf-date\">{bd}</span>",
      "compare.gap": "{higher} kwɔ, kɛ {gap}.",
      "real.rate": "Shikatoohe jara ji <b>{policy}%</b> ({policyDate}), ni jara ni miiwo nɔ ji <b>{inflation}%</b> ({inflationDate}), no hewɔ lɛ jara diɛŋtsɛ ji <b>{real}%</b> {direction}.",
      "above": "yɛ nɔ",
      "below": "yɛ shishi",
      "africa.gdp": "{country} shikatsɔɔmɔ ji aaafee US${gdp}bn ({year}).",
      "africa.open": "Gbele Afrika baafo lɛ",
      "voice.none": "Nɔ nɛɛ bɛ {language} gbee, no hewɔ mikaneɔ yɛ Blɔfo mli. Wiemɔi ni yɔɔ baafo lɛ nɔ lɛ, amɛyɛ {language} mli lolo.",
      "note.figures": "Akɔntabuu gbɛi komɛi kã Blɔfo wiemɔ mli lolo."
    },
    voiceHints: ["gaa", "en-GH", "en-NG"],
    labels: {
      "Inflation": "Jara ni miiwo nɔ",
      "Food inflation": "Niyenii ajara ni miiwo nɔ",
      "BoG policy rate": "Shikatoohe lɛ deme",
      "US dollar": "Amerika dollar",
      "British pound": "Britain pound",
      "Euro": "Euro",
      "Gold price": "Shika tsuru jara",
      "Cocoa world price": "Kookoo jara yɛ je lɛ fɛɛ mli",
      "Petrol": "Petrol",
      "Diesel": "Diesel",
      "Cooking gas (LPG)": "Niishaa gas (LPG)",
      "Daily minimum wage": "Daa nyɔmɔwoo ni fe fioo",
      "Gross reserves": "Maŋsɛɛ shika ni ato",
      "Trade surplus": "Jarayeli sɛɛnamɔ",
      "Real GDP growth": "Shikatsɔɔmɔ shwiemɔ (GDP)",
      "Unemployment rate": "Nitsumɔ ni bɛ"
    },
    suggestions: [
      "Nyɔmɔ lɛ yɛ mɛni amrɔ?", "Mɔ fɛɛ mɔ nyɔmɔ ji mɛni?", "Jara ni miiwo nɔ ji mɛni?",
      "Dollar kɛ cedi", "Nibii ni ahɔɔ kɛ nibii ni aje", "Gbi kpeteŋkpele ni nyiɛ sɛɛ?",
      "Ani shikatoohe jara kwɔ fe jara ni miiwo nɔ?", "Be mli jara ni miiwo nɔ kwɔ fe fɛɛ?"
    ],
    ask: {
      debt: ["nyɔmɔ", "nyomo", "shika ni ahiɛ"],
      inflation: ["jara", "jara wo nɔ", "jara ni miiwo nɔ"],
      dollar: ["dollar", "cedi", "shika"],
      population: ["gbɔmɛi ayibɔ", "mɛi ayibɔ"],
      holiday: ["gbi kpeteŋkpele", "hejɔɔmɔ gbi"],
      trade: ["nitsumɔ", "hɔɔmɔ", "jarayeli"],
      budget: ["shika gbɛjianɔtoo", "too"],
      hello: ["ojekoo", "bawo", "ŋmɛnɛ"],
      help: ["ye bua mi", "namɔ ji bo"],
      thanks: ["oyiwaladɔŋŋ", "oyiwala", "daaŋŋ"],
      bye: ["yaa oyaawɔ", "oyaawɔ", "miiya"],
      howareyou: ["te oyɔɔ tɛŋŋ", "bo oyɔɔ"]
    }
  },

  ha: {
    name: "Hausa",
    speech: "ha-NG",
    strings: {
      "ui.placeholder": "Tambaya game da bashi, farashi ko dala…",
      "ui.send": "Tambaya",
      "ui.listening": "Ina saurare…",
      "ui.noSpeech": "Ban ji ba. Sake fada, ko ka rubuta.",
      "ui.micBlocked": "An toshe makurufo. Ka bada izini a browser dinka, ko ka rubuta tambayar.",
      "ui.micNone": "Wannan browser ba ya iya saurara. Chrome a Android ko kwamfuta ya fi dacewa.",
      "greeting": "Sannu — ni ne <b>Alfredo</b>. Tambaye ni game da bashin Ghana, hauhawan farashi, cedi, ciniki ko kasafin kudi, zan amsa daga alkaluman da ke wannan shafin, tare da ranar kowanne.",
      "iam": "Na’am, ina nan. Ta yaya zan taimaka maka yau?",
      "thanks": "Ba komai. Akwai wani abu kuma da zan taimaka maka?",
      "bye": "Sai an jima. Ka dawo kowane lokaci — alkaluman suna sabuntawa kullum.",
      "howareyou": "Ina lafiya, na gode. A shirye nake da alkaluma duk lokacin da kake bukata.",
      "hello": "Sannu. Ina amsa daga alkaluman wannan shafin — bashi, farashi, cedi, ciniki da kasafin kudi. Gwada daya daga cikin tambayoyin da ke kasa, ko ka rubuta naka.",
      "help": "Ina karanta bayanan wannan shafin: alkaluma {count} da aka wallafa, karatun bashi, kasafin kudi, kalandar kasa da jerin shekaru tun 1993. Zan iya ba ka alkalami, ranarsa, yadda ya sauya, da yadda ake lissafa masu tafiya. Ba na shiga intanet.",
      "unknown": "Ban riƙe wannan ba. Zan iya amsa duk abin da ke wannan shafin — kowanne daga alkaluma {count}, ma'aunin bashi, kasafin kudi, ciniki, kalanda, ko yadda ake lissafa alkalami. Ka ambaci sunan alkalami, misali \"hauhawan farashi\" ko \"farashin zinari\".",
      "debt.total": "<b>{now}</b> a yanzu — kiyasi mai gudana. Yana ƙidaya gaba daga alkalamin Babban Bankin Ghana na {latestLabel} wato {latest}, kan {perSecond} a duk dakika, bisa saurin da aka auna tsakanin {prevLabel} da {latestLabel}.",
      "debt.percap": "<b>{value}</b> ga kowane mutum, a yanzu. Wannan shi ne kiyasin bashi da aka raba kan yawan jama'a {pop}.",
      "debt.household": "Ga gida mai mutum {n}: <b>{share}</b> na bashin, kuma an ciwo {ytd} da sunansu a wannan shekarar.",
      "debt.domestic": "<b>{value}</b> bashin cikin gida, kaso {share}% na jimlar a {label}.",
      "debt.external": "<b>{value}</b> bashin waje, kaso {share}% na jimlar. Yawancinsa na kudin waje ne, don haka faduwar cedi na kara shi ba tare da sabon bashi ba.",
      "debt.ratio": "<b>{live}%</b> na GDP bisa kiyasin yanzu; an bayar da rahoton {reported}% a {label}, idan aka kwatanta da matuka {peak}% a {peakLabel}.",
      "debt.today": "<b>{value}</b> aka ciwo tun tsakar dare, bisa saurin yanzu.",
      "debt.ytd": "<b>{value}</b> aka kara tun karatun {label}.",
      "debt.rate": "Bashin na karuwa kusan <b>{perSecond} a duk dakika</b> — miliyan {perDay} a rana, bisa saurin tsakanin {prevLabel} da {latestLabel}.",
      "population": "Kimanin mutane <b>{pop}</b>, daga kiyasin {source} na miliyan {base} a 1 ga Yuli 2026, mai karuwa {growth}% a shekara.",
      "method": "Ma'aunan kiyasi ne tsakanin sanarwar hukuma. Bashi na ƙidaya gaba daga karatun {label} bisa saurin watanni {months} da suka gabata. Layukan kasafin kudi ana raba alkaluman shekara daidai kan shekarar. Kowane alkalami yana da ranarsa, kuma duk wanda lokacinsa ya wuce ana yi masa alama <b>Update due</b>.",
      "budget": "<b>{label}: {value}</b> aka amince da shi na {year}, wato kusan {toDate} har zuwa yau.",
      "trade": "Kayan da aka fitar <b>US${exports}bn</b> a {period}, zinari ya kai US${gold}bn. Kayan shigowa kusan <b>US${imports}bn</b>, don haka ribar ciniki ita ce US${surplus}bn.",
      "calendar": "Na gaba: {list}.",
      "calendar.item": "<b>{name}</b> a {date}",
      "news": "Sabbin labaran kasuwanci:",
      "africa.country": "<b>{country}: {value}%</b> ({period}) idan aka kwatanta da Ghana {ghana}% ({ghanaPeriod}) — Ghana ta fi {direction} da maki {gap}.",
      "africa.rank": "Hauhawan farashin Ghana <b>{ghana}%</b> ({period}) ita ce ta {rank} mafi yawa cikin kasashen Afirka {count}. Mafi yawa: {highest} da {highestValue}%. Mafi karanci: {lowest} da {lowestValue}%.",
      "reading": "<b>{label}: {value}</b> <span class=\"alf-date\">{date}</span>",
      "reading.live": "Farashin kasuwa yanzu: {value}, da {time}.",
      "reading.up": "Ya haura daga {from} a {fromDate}.",
      "reading.down": "Ya sauka daga {from} a {fromDate}.",
      "reading.flat": "Bai sauya ba tun {fromDate}.",
      "reading.range": "Tun {since}: mafi yawa {high}, mafi karanci {low}.",
      "higher": "sama",
      "lower": "kasa",
      "reading.from": "Daga: {source} · {date}.",
      "reading.open": "Duba cikakken alkalami",
      "reading.fromShort": "{source}",
      "unknown.near": "Ban tabbata ina da wannan ba. Ko kana nufin:",
      "follow.why": "A kan <b>{label}</b>:",
      "follow.source": "<b>{label}</b> yana fitowa daga:",
      "change": "<b>{label}</b> ya {direction} daga {from} ({fromDate}) zuwa {to} ({toDate}) — canjin {gap}.",
      "change.pct": "Wannan canji ne na {pct}%.",
      "rose": "hau",
      "fell": "sauka",
      "held": "tsaya haka",
      "extreme.high": "<b>{label}</b> ya fi yawa a {value} a {date} — tun {since}. Yanzu yana {now} ({nowDate}).",
      "extreme.low": "<b>{label}</b> ya fi karanci a {value} a {date} — tun {since}. Yanzu yana {now} ({nowDate}).",
      "compare": "<b>{a}: {av}</b> <span class=\"alf-date\">{ad}</span> da <b>{b}: {bv}</b> <span class=\"alf-date\">{bd}</span>",
      "compare.gap": "{higher} ya fi, da {gap}.",
      "real.rate": "Ma'aunin banki shi ne <b>{policy}%</b> ({policyDate}), hauhawan farashi kuma <b>{inflation}%</b> ({inflationDate}), don haka ainihin ma'auni yana kusan <b>{real}%</b> {direction}.",
      "above": "sama da hauhawan farashi",
      "below": "kasa da hauhawan farashi",
      "africa.gdp": "Tattalin arzikin {country} kusan US${gdp}bn ne ({year}).",
      "africa.open": "Bude shafin Afirka",
      "voice.none": "Wannan na'urar ba ta da muryar {language}, don haka ina karantawa da Turanci. Rubutun da ke allon yana nan da {language}.",
      "note.figures": "Sunayen wasu alkaluma na nan cikin Turanci."
    },
    voiceHints: ["ha", "ha-NG", "en-NG", "en-GH"],
    labels: {
      "Inflation": "Hauhawan farashi",
      "Food inflation": "Hauhawan farashin abinci",
      "BoG policy rate": "Adadin manufar babban banki",
      "91-day T-bill": "Takardar kwana 91",
      "364-day T-bill": "Takardar kwana 364",
      "US dollar": "Dalar Amurka",
      "British pound": "Fam na Biritaniya",
      "Euro": "Yuro",
      "Gold price": "Farashin zinari",
      "Cocoa world price": "Farashin koko a duniya",
      "Petrol": "Fetur",
      "Diesel": "Dizal",
      "Cooking gas (LPG)": "Iskar girki (LPG)",
      "Daily minimum wage": "Mafi karancin albashi na yini",
      "Gross reserves": "Ajiyar kudaden waje",
      "Trade surplus": "Ribar ciniki",
      "Real GDP growth": "Cigaban tattalin arziki",
      "Unemployment rate": "Rashin aikin yi"
    },
    suggestions: [
      "Nawa ne bashin yanzu?", "Nawa kowane mutum ke bin bashi?", "Nawa ne hauhawan farashi?",
      "Dala da cedi", "Kaya fita da kaya shigowa", "Yaushe ne babban ranar gaba?",
      "Ma'aunin banki ya fi hauhawan farashi?", "Yaushe hauhawan farashi ya fi yawa?"
    ],
    ask: {
      debt: ["bashi", "bashin kasa", "utang"],
      percap: ["kowane mutum", "ga kowa"],
      inflation: ["hauhawan farashi", "farashi"],
      dollar: ["dala", "cedi", "musaya"],
      population: ["yawan jama'a", "mutane nawa"],
      holiday: ["hutu", "babbar rana", "babban rana", "ranar hutu", "bikin"],
      trade: ["ciniki", "fitarwa", "shigowa"],
      budget: ["kasafin kudi", "haraji"],
      hello: ["sannu", "barka", "ina kwana", "ina wuni"],
      help: ["taimaka min", "wanene kai"],
      thanks: ["na gode", "mun gode", "godiya"],
      bye: ["sai an jima", "sallama", "sai anjima"],
      howareyou: ["yaya kake", "ina kwana", "kana lafiya"]
    }
  }
};
